apiVersion: cassandraoperator.instaclustr.com/v1alpha1
kind: CassandraBackup
metadata:
  name: test-cassandra-backup
  labels:
    app: cassandra
spec:
  cdc: test-cluster-dc1-cassandra
  cluster: test-cluster
  datacenter: dc1
  storageLocation: "s3://cassandra-bucket"
  snapshotTag: "mySnapshotTag"
  secret: cloud-backup-secrets
  globalRequest: true
#justCreate: true
